name: Compile LaTeX document
on:
  push:
    paths:
      - '*.tex'
      - 'pre-textuais/*.tex'
      - 'textuais/*.tex'
    branches:    
      - main       
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=TCC main.tex"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: ':robot: Using action to produce pdf from latex'
          add: '*.pdf'
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
          ref: main

